// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeRequested():Promise<boolean>

export function RequestChange():Promise<void>

export function Version():Promise<string>
