// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeRequested() {
  return window['go']['main']['App']['ChangeRequested']();
}

export function RequestChange() {
  return window['go']['main']['App']['RequestChange']();
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
